sudo: required
language: python

addons:
    apt:
        update: true

python:
    - "3.7-dev"

services:
    - docker


install:
    - pip install --upgrade setuptools aiodns cchardet ujson aiohttp asyncio beautifulsoup4 certifi

before_script:
    - git clone https://github.com/ShyPixie/stlib
    - cd stlib/src/steam_api
    - docker login -u shypixie -p $DOCKER_SECRET
    - image_id=$(docker create shypixie/steamworks_sdk)
    - docker cp $image_id:steamworks_sdk - > steamworks.tar.gz
    - tar xfv steamworks.tar.gz
    - cd ../..
    - python setup.py build
    - python setup.py install
    - cd ..

script:
    - python setup.py build
    - python setup.py install

env:
  global:
    secure: mpe8NMXHtWKlg+xWDbohfp/usFkA4p3Ot6b+FwOArXRBznbtZx4qOL076txxY53IlZT4xPtPZgpm8y5n8e/dV4F2BBFI//T5faQ4YsPlQAdWsRDFrnDb7Egh71sYn7RfZ95d/dYvUJmOeghXVQ3t/mIJup3JNRaJ9Y55hOJRcyjZKE2GzKn4NOx8lfHEcFwO6+ELEfce+urrFf7FngoYwGVZZAxowuKYtDCgoL1brIFopcE0ZLyaOoQbl21fOsblMWRCgVoV8yu6u+aQdVBtPxNIETL6O4//Pt+HTiwt3Td/a9Z/wCL6Gdc8vc+XKRrSj3/X3HLobjW5410Q8YkCf77VEFLDC4E7gFCrdmBhk/RvxyzpWeZLjjYe+TCJ1IPpLddWyGcmPUpMv7MQaI6APk5orL6P2aDD+qOIiOeyjQ2iwJTuvA1jxjKRVWqYyjWaMFSg+T/J46DcDnvm3ErKP1iUVRqvQ0U1bwzNyj3xaGhywAGVS8J36ZeIeaC8ymAXiWXh3n4E4LjSpX4sYaWI08WVwhu7H/RJSYhi5hH5W7jtFo3uJlY/mtnlNqZ0Ms8sC3jRA1DzM1TA8+u5nPIJJdKIhh8lIVSxK+MYYx0ywf+T+QIoaHvB4z0vu9eCcMcOJXY5P2RGp96jHRRResSJXLTBhqk7Y7xPmdWL46knuG0=

